from enum import Enum

class BillingCycle(str, Enum):
    BILLING_CYCLE_UNSPECIFIED = "BILLING_CYCLE_UNSPECIFIED",
    BILLING_CYCLE_MONTHLY = "BILLING_CYCLE_MONTHLY",
    BILLING_CYCLE_YEARLY = "BILLING_CYCLE_YEARLY",

