from enum import Enum

class InvoiceStatus(str, Enum):
    INVOICE_STATUS_UNSPECIFIED = "INVOICE_STATUS_UNSPECIFIED",
    INVOICE_STATUS_DRAFT = "INVOICE_STATUS_DRAFT",
    INVOICE_STATUS_OPEN = "INVOICE_STATUS_OPEN",
    INVOICE_STATUS_PAID = "INVOICE_STATUS_PAID",
    INVOICE_STATUS_VOID = "INVOICE_STATUS_VOID",
    INVOICE_STATUS_UNCOLLECTIBLE = "INVOICE_STATUS_UNCOLLECTIBLE",

