from enum import Enum

class PlanType(str, Enum):
    PLAN_TYPE_UNSPECIFIED = "PLAN_TYPE_UNSPECIFIED",
    PLAN_TYPE_FREE = "PLAN_TYPE_FREE",
    PLAN_TYPE_PAY_AS_YOU_GO = "PLAN_TYPE_PAY_AS_YOU_GO",
    PLAN_TYPE_PRO = "PLAN_TYPE_PRO",
    PLAN_TYPE_CUSTOM = "PLAN_TYPE_CUSTOM",

