from enum import Enum

class SalesLeadStatus(str, Enum):
    SALES_LEAD_STATUS_UNSPECIFIED = "SALES_LEAD_STATUS_UNSPECIFIED",
    SALES_LEAD_STATUS_NEW = "SALES_LEAD_STATUS_NEW",
    SALES_LEAD_STATUS_CONTACTED = "SALES_LEAD_STATUS_CONTACTED",
    SALES_LEAD_STATUS_QUALIFIED = "SALES_LEAD_STATUS_QUALIFIED",
    SALES_LEAD_STATUS_CLOSED = "SALES_LEAD_STATUS_CLOSED",

