from enum import Enum

class SubscriptionStatus(str, Enum):
    SUBSCRIPTION_STATUS_UNSPECIFIED = "SUBSCRIPTION_STATUS_UNSPECIFIED",
    SUBSCRIPTION_STATUS_ACTIVE = "SUBSCRIPTION_STATUS_ACTIVE",
    SUBSCRIPTION_STATUS_INACTIVE = "SUBSCRIPTION_STATUS_INACTIVE",
    SUBSCRIPTION_STATUS_CANCELED = "SUBSCRIPTION_STATUS_CANCELED",
    SUBSCRIPTION_STATUS_EXPIRED = "SUBSCRIPTION_STATUS_EXPIRED",
    SUBSCRIPTION_STATUS_PENDING = "SUBSCRIPTION_STATUS_PENDING",
    SUBSCRIPTION_STATUS_SUSPENDED = "SUBSCRIPTION_STATUS_SUSPENDED",
    SUBSCRIPTION_STATUS_TRIALING = "SUBSCRIPTION_STATUS_TRIALING",
    SUBSCRIPTION_STATUS_PAST_DUE = "SUBSCRIPTION_STATUS_PAST_DUE",
    SUBSCRIPTION_STATUS_UNPAID = "SUBSCRIPTION_STATUS_UNPAID",
    SUBSCRIPTION_STATUS_INCOMPLETE = "SUBSCRIPTION_STATUS_INCOMPLETE",
    SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED = "SUBSCRIPTION_STATUS_INCOMPLETE_EXPIRED",
    SUBSCRIPTION_STATUS_PAUSED = "SUBSCRIPTION_STATUS_PAUSED",

