from enum import Enum

class FileStatus(str, Enum):
    FILE_STATUS_UNSPECIFIED = "FILE_STATUS_UNSPECIFIED",
    FILE_STATUS_UPLOADING = "FILE_STATUS_UPLOADING",
    FILE_STATUS_UPLOADED = "FILE_STATUS_UPLOADED",
    FILE_STATUS_PROCESSING = "FILE_STATUS_PROCESSING",
    FILE_STATUS_PREPARING = "FILE_STATUS_PREPARING",
    FILE_STATUS_READY = "FILE_STATUS_READY",
    FILE_STATUS_ERROR = "FILE_STATUS_ERROR",

