from enum import Enum

class ImageFormat(str, Enum):
    IMAGE_FORMAT_UNSPECIFIED = "IMAGE_FORMAT_UNSPECIFIED",
    IMAGE_FORMAT_JPG = "IMAGE_FORMAT_JPG",
    IMAGE_FORMAT_PNG = "IMAGE_FORMAT_PNG",
    IMAGE_FORMAT_WEBP = "IMAGE_FORMAT_WEBP",
    IMAGE_FORMAT_GIF = "IMAGE_FORMAT_GIF",

