from enum import Enum

class SubtitleFormat(str, Enum):
    SUBTITLE_FORMAT_UNSPECIFIED = "SUBTITLE_FORMAT_UNSPECIFIED",
    SUBTITLE_FORMAT_SRT = "SUBTITLE_FORMAT_SRT",
    SUBTITLE_FORMAT_VTT = "SUBTITLE_FORMAT_VTT",

