from enum import Enum

class Visibility(str, Enum):
    VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED",
    VISIBILITY_PUBLIC = "VISIBILITY_PUBLIC",
    VISIBILITY_UNLISTED = "VISIBILITY_UNLISTED",
    VISIBILITY_PRIVATE = "VISIBILITY_PRIVATE",

