# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_sdk.api.feeds_api import FeedsApi


class TestFeedsApi(unittest.TestCase):
    """FeedsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedsApi()

    def tearDown(self) -> None:
        pass

    def test_feeds_feed_id_creators_creator_id_get(self) -> None:
        """Test case for feeds_feed_id_creators_creator_id_get

        List posts by creator
        """
        pass

    def test_feeds_feed_id_get(self) -> None:
        """Test case for feeds_feed_id_get

        List posts in a feed
        """
        pass

    def test_feeds_feed_id_post_id_get(self) -> None:
        """Test case for feeds_feed_id_post_id_get

        Get a post
        """
        pass


if __name__ == '__main__':
    unittest.main()
