# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rixl_sdk.api.videos_api import VideosApi


class TestVideosApi(unittest.TestCase):
    """VideosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VideosApi()

    def tearDown(self) -> None:
        pass

    def test_videos_get(self) -> None:
        """Test case for videos_get

        List videos for a project
        """
        pass

    def test_videos_languages_get(self) -> None:
        """Test case for videos_languages_get

        List available subtitle languages
        """
        pass

    def test_videos_upload_complete_post(self) -> None:
        """Test case for videos_upload_complete_post

        Upload: Mark as complete
        """
        pass

    def test_videos_upload_init_post(self) -> None:
        """Test case for videos_upload_init_post

        Upload: Init
        """
        pass

    def test_videos_video_id_audio_tracks_delete(self) -> None:
        """Test case for videos_video_id_audio_tracks_delete

        Delete all audio tracks
        """
        pass

    def test_videos_video_id_audio_tracks_lang_code_delete(self) -> None:
        """Test case for videos_video_id_audio_tracks_lang_code_delete

        Delete audio track by language
        """
        pass

    def test_videos_video_id_audio_tracks_lang_code_put(self) -> None:
        """Test case for videos_video_id_audio_tracks_lang_code_put

        Upsert video audio track
        """
        pass

    def test_videos_video_id_audio_tracks_post(self) -> None:
        """Test case for videos_video_id_audio_tracks_post

        Bulk upsert video audio tracks
        """
        pass

    def test_videos_video_id_audio_tracks_track_id_delete(self) -> None:
        """Test case for videos_video_id_audio_tracks_track_id_delete

        Delete audio track
        """
        pass

    def test_videos_video_id_chapters_delete(self) -> None:
        """Test case for videos_video_id_chapters_delete

        Delete video chapters
        """
        pass

    def test_videos_video_id_chapters_put(self) -> None:
        """Test case for videos_video_id_chapters_put

        Update video chapters
        """
        pass

    def test_videos_video_id_delete_delete(self) -> None:
        """Test case for videos_video_id_delete_delete

        Delete video
        """
        pass

    def test_videos_video_id_get(self) -> None:
        """Test case for videos_video_id_get

        Get a video
        """
        pass

    def test_videos_video_id_subtitles_delete(self) -> None:
        """Test case for videos_video_id_subtitles_delete

        Delete all subtitles
        """
        pass

    def test_videos_video_id_subtitles_lang_code_delete(self) -> None:
        """Test case for videos_video_id_subtitles_lang_code_delete

        Delete subtitle by language
        """
        pass

    def test_videos_video_id_subtitles_lang_code_put(self) -> None:
        """Test case for videos_video_id_subtitles_lang_code_put

        Upsert video subtitle
        """
        pass

    def test_videos_video_id_subtitles_post(self) -> None:
        """Test case for videos_video_id_subtitles_post

        Bulk upsert video subtitles
        """
        pass

    def test_videos_video_id_subtitles_subtitle_id_delete(self) -> None:
        """Test case for videos_video_id_subtitles_subtitle_id_delete

        Delete subtitle
        """
        pass

    def test_videos_video_id_thumbnail_put(self) -> None:
        """Test case for videos_video_id_thumbnail_put

        Update video thumbnail
        """
        pass


if __name__ == '__main__':
    unittest.main()
