from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.authv1.verify_email_response import VerifyEmailResponse
    from .....models.gateway.verify_email_body import VerifyEmailBody
    from .resend.resend_request_builder import ResendRequestBuilder

class VerifyRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /auth/v1/email/verify
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new VerifyRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/auth/v1/email/verify", path_parameters)
    
    async def post(self,body: VerifyEmailBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[VerifyEmailResponse]:
        """
        Verifies a user's email address using a verification id and the code sent to them.
        param body: Verification id and code
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[VerifyEmailResponse]
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = self.to_post_request_information(
            body, request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .....models.authv1.verify_email_response import VerifyEmailResponse

        return await self.request_adapter.send_async(request_info, VerifyEmailResponse, None)
    
    def to_post_request_information(self,body: VerifyEmailBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Verifies a user's email address using a verification id and the code sent to them.
        param body: Verification id and code
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = RequestInformation(Method.POST, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
        return request_info
    
    def with_url(self,raw_url: str) -> VerifyRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: VerifyRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return VerifyRequestBuilder(self.request_adapter, raw_url)
    
    @property
    def resend(self) -> ResendRequestBuilder:
        """
        The resend property
        """
        from .resend.resend_request_builder import ResendRequestBuilder

        return ResendRequestBuilder(self.request_adapter, self.path_parameters)
    
    @dataclass
    class VerifyRequestBuilderPostRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

