# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FileStatus(str, Enum):
    """
    FileStatus
    """

    """
    allowed enum values
    """
    FileStatusUploading = 'uploading'
    FileStatusUploaded = 'uploaded'
    FileStatusProcessing = 'processing'
    FileStatusPreparing = 'preparing'
    FileStatusReady = 'ready'
    FileStatusError = 'error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileStatus from a JSON string"""
        return cls(json.loads(json_str))


