# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from rixl_api.models.chapter import Chapter
from rixl_api.models.file import File
from rixl_api.models.github_com_qeeqez_api_db_sqlc_plan_type import GithubComQeeqezApiDbSqlcPlanType
from rixl_api.models.image import Image
from typing import Optional, Set
from typing_extensions import Self

class GithubComQeeqezApiInternalVideosVideoResponse(BaseModel):
    """
    GithubComQeeqezApiInternalVideosVideoResponse
    """ # noqa: E501
    bitrate: Optional[StrictInt] = None
    chapters: Optional[List[Chapter]] = None
    codec: Optional[StrictStr] = None
    duration: Optional[Union[StrictFloat, StrictInt]] = None
    file: Optional[File] = None
    framerate: Optional[StrictStr] = None
    hdr: Optional[StrictBool] = None
    height: Optional[StrictInt] = None
    id: Optional[StrictStr] = None
    plan_type: Optional[GithubComQeeqezApiDbSqlcPlanType] = None
    poster: Optional[Image] = None
    width: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["bitrate", "chapters", "codec", "duration", "file", "framerate", "hdr", "height", "id", "plan_type", "poster", "width"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubComQeeqezApiInternalVideosVideoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in chapters (list)
        _items = []
        if self.chapters:
            for _item_chapters in self.chapters:
                if _item_chapters:
                    _items.append(_item_chapters.to_dict())
            _dict['chapters'] = _items
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of poster
        if self.poster:
            _dict['poster'] = self.poster.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubComQeeqezApiInternalVideosVideoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bitrate": obj.get("bitrate"),
            "chapters": [Chapter.from_dict(_item) for _item in obj["chapters"]] if obj.get("chapters") is not None else None,
            "codec": obj.get("codec"),
            "duration": obj.get("duration"),
            "file": File.from_dict(obj["file"]) if obj.get("file") is not None else None,
            "framerate": obj.get("framerate"),
            "hdr": obj.get("hdr"),
            "height": obj.get("height"),
            "id": obj.get("id"),
            "plan_type": obj.get("plan_type"),
            "poster": Image.from_dict(obj["poster"]) if obj.get("poster") is not None else None,
            "width": obj.get("width")
        })
        return _obj


