# coding: utf-8

"""
    RIXL API

    **Build a powerful video experience from on-demand streaming to dynamic social feeds with a single API.**  RIXL handles video processing, ingestion and global delivery so you don't have to. With builtin support for transcoding, storage and structured media feeds, Our API makes it easy to deliver high-quality media content at scale.

    The version of the OpenAPI document: 2.0
    Contact: support@rixl.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rixl_api.models.github_com_qeeqez_api_db_sqlc_plan_type import GithubComQeeqezApiDbSqlcPlanType
from rixl_api.models.github_com_qeeqez_api_internal_videos_video_response import GithubComQeeqezApiInternalVideosVideoResponse
from rixl_api.models.image import Image
from rixl_api.models.post_type import PostType
from typing import Optional, Set
from typing_extensions import Self

class Post(BaseModel):
    """
    Post
    """ # noqa: E501
    created_at: Optional[StrictStr] = None
    creator_id: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    feed_id: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    image: Optional[Image] = None
    plan_type: Optional[GithubComQeeqezApiDbSqlcPlanType] = None
    type: Optional[PostType] = None
    updated_at: Optional[StrictStr] = None
    video: Optional[GithubComQeeqezApiInternalVideosVideoResponse] = None
    __properties: ClassVar[List[str]] = ["created_at", "creator_id", "description", "feed_id", "id", "image", "plan_type", "type", "updated_at", "video"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Post from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of video
        if self.video:
            _dict['video'] = self.video.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Post from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "creator_id": obj.get("creator_id"),
            "description": obj.get("description"),
            "feed_id": obj.get("feed_id"),
            "id": obj.get("id"),
            "image": Image.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "plan_type": obj.get("plan_type"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "video": GithubComQeeqezApiInternalVideosVideoResponse.from_dict(obj["video"]) if obj.get("video") is not None else None
        })
        return _obj


