from enum import Enum

class MessageAuthor(str, Enum):
    MESSAGE_AUTHOR_UNSPECIFIED = "MESSAGE_AUTHOR_UNSPECIFIED",
    MESSAGE_AUTHOR_CUSTOMER = "MESSAGE_AUTHOR_CUSTOMER",
    MESSAGE_AUTHOR_AGENT = "MESSAGE_AUTHOR_AGENT",
    MESSAGE_AUTHOR_SYSTEM = "MESSAGE_AUTHOR_SYSTEM",

