from enum import Enum

class TicketPriority(str, Enum):
    TICKET_PRIORITY_UNSPECIFIED = "TICKET_PRIORITY_UNSPECIFIED",
    TICKET_PRIORITY_LOW = "TICKET_PRIORITY_LOW",
    TICKET_PRIORITY_NORMAL = "TICKET_PRIORITY_NORMAL",
    TICKET_PRIORITY_HIGH = "TICKET_PRIORITY_HIGH",
    TICKET_PRIORITY_URGENT = "TICKET_PRIORITY_URGENT",

