from enum import Enum

class TicketStatus(str, Enum):
    TICKET_STATUS_UNSPECIFIED = "TICKET_STATUS_UNSPECIFIED",
    TICKET_STATUS_OPEN = "TICKET_STATUS_OPEN",
    TICKET_STATUS_PENDING = "TICKET_STATUS_PENDING",
    TICKET_STATUS_RESOLVED = "TICKET_STATUS_RESOLVED",
    TICKET_STATUS_CLOSED = "TICKET_STATUS_CLOSED",

