from enum import Enum

class ExternalAccountProvider(str, Enum):
    EXTERNAL_ACCOUNT_PROVIDER_UNSPECIFIED = "EXTERNAL_ACCOUNT_PROVIDER_UNSPECIFIED",
    EXTERNAL_ACCOUNT_PROVIDER_GOOGLE = "EXTERNAL_ACCOUNT_PROVIDER_GOOGLE",
    EXTERNAL_ACCOUNT_PROVIDER_APPLE = "EXTERNAL_ACCOUNT_PROVIDER_APPLE",
    EXTERNAL_ACCOUNT_PROVIDER_MICROSOFT = "EXTERNAL_ACCOUNT_PROVIDER_MICROSOFT",
    EXTERNAL_ACCOUNT_PROVIDER_FACEBOOK = "EXTERNAL_ACCOUNT_PROVIDER_FACEBOOK",
    EXTERNAL_ACCOUNT_PROVIDER_TELEGRAM = "EXTERNAL_ACCOUNT_PROVIDER_TELEGRAM",

