from enum import Enum

class MembershipApplicationState(str, Enum):
    MEMBERSHIP_APPLICATION_STATE_UNSPECIFIED = "MEMBERSHIP_APPLICATION_STATE_UNSPECIFIED",
    MEMBERSHIP_APPLICATION_STATE_PENDING = "MEMBERSHIP_APPLICATION_STATE_PENDING",
    MEMBERSHIP_APPLICATION_STATE_APPROVED = "MEMBERSHIP_APPLICATION_STATE_APPROVED",
    MEMBERSHIP_APPLICATION_STATE_DECLINED = "MEMBERSHIP_APPLICATION_STATE_DECLINED",
    MEMBERSHIP_APPLICATION_STATE_CANCELLED = "MEMBERSHIP_APPLICATION_STATE_CANCELLED",

