from enum import Enum

class MembershipState(str, Enum):
    MEMBERSHIP_STATE_UNSPECIFIED = "MEMBERSHIP_STATE_UNSPECIFIED",
    MEMBERSHIP_STATE_PENDING = "MEMBERSHIP_STATE_PENDING",
    MEMBERSHIP_STATE_ACCEPTED = "MEMBERSHIP_STATE_ACCEPTED",
    MEMBERSHIP_STATE_DECLINED = "MEMBERSHIP_STATE_DECLINED",

