from enum import Enum

class MembershipState(str, Enum):
    MEMBERSHIP_STATE_UNSPECIFIED = "MEMBERSHIP_STATE_UNSPECIFIED",
    MEMBERSHIP_STATE_ACTIVE = "MEMBERSHIP_STATE_ACTIVE",
    MEMBERSHIP_STATE_SUSPENDED = "MEMBERSHIP_STATE_SUSPENDED",
    MEMBERSHIP_STATE_LEFT = "MEMBERSHIP_STATE_LEFT",
    MEMBERSHIP_STATE_REMOVED = "MEMBERSHIP_STATE_REMOVED",

