from enum import Enum

class MembershipRole(str, Enum):
    MEMBERSHIP_ROLE_UNSPECIFIED = "MEMBERSHIP_ROLE_UNSPECIFIED",
    MEMBERSHIP_ROLE_OWNER = "MEMBERSHIP_ROLE_OWNER",
    MEMBERSHIP_ROLE_ADMIN = "MEMBERSHIP_ROLE_ADMIN",
    MEMBERSHIP_ROLE_MEMBER = "MEMBERSHIP_ROLE_MEMBER",

