from enum import Enum

class PolicyIdentityType(str, Enum):
    POLICY_IDENTITY_TYPE_UNSPECIFIED = "POLICY_IDENTITY_TYPE_UNSPECIFIED",
    POLICY_IDENTITY_TYPE_USER = "POLICY_IDENTITY_TYPE_USER",
    POLICY_IDENTITY_TYPE_API_KEY = "POLICY_IDENTITY_TYPE_API_KEY",
    POLICY_IDENTITY_TYPE_CLIENTAUTH_CREDENTIAL = "POLICY_IDENTITY_TYPE_CLIENTAUTH_CREDENTIAL",

