from enum import Enum

class ExportFormat(str, Enum):
    EXPORT_FORMAT_UNSPECIFIED = "EXPORT_FORMAT_UNSPECIFIED",
    EXPORT_FORMAT_CSV = "EXPORT_FORMAT_CSV",
    EXPORT_FORMAT_XLSX = "EXPORT_FORMAT_XLSX",
    EXPORT_FORMAT_PDF = "EXPORT_FORMAT_PDF",
    EXPORT_FORMAT_JSON = "EXPORT_FORMAT_JSON",

