from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.authv1.list_memberships_response import ListMembershipsResponse

class PendingRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /auth/v1/memberships/pending
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new PendingRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/auth/v1/memberships/pending{?limit*,offset*}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[PendingRequestBuilderGetQueryParameters]] = None) -> Optional[ListMembershipsResponse]:
        """
        Returns a paginated list of the authenticated user's pending organization membership invitations that have not yet been accepted.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[ListMembershipsResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .....models.authv1.list_memberships_response import ListMembershipsResponse

        return await self.request_adapter.send_async(request_info, ListMembershipsResponse, None)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[PendingRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        Returns a paginated list of the authenticated user's pending organization membership invitations that have not yet been accepted.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> PendingRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: PendingRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return PendingRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class PendingRequestBuilderGetQueryParameters():
        """
        Returns a paginated list of the authenticated user's pending organization membership invitations that have not yet been accepted.
        """
        # Limit
        limit: Optional[int] = None

        # Offset
        offset: Optional[int] = None

    
    @dataclass
    class PendingRequestBuilderGetRequestConfiguration(RequestConfiguration[PendingRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

