from enum import Enum

class ClientCredentialStatus(str, Enum):
    CLIENT_CREDENTIAL_STATUS_UNSPECIFIED = "CLIENT_CREDENTIAL_STATUS_UNSPECIFIED",
    CLIENT_CREDENTIAL_STATUS_ACTIVE = "CLIENT_CREDENTIAL_STATUS_ACTIVE",
    CLIENT_CREDENTIAL_STATUS_REVOKED = "CLIENT_CREDENTIAL_STATUS_REVOKED",

