from enum import Enum

class VideoQuality(str, Enum):
    VIDEO_QUALITY_UNSPECIFIED = "VIDEO_QUALITY_UNSPECIFIED",
    VIDEO_QUALITY_BASIC = "VIDEO_QUALITY_BASIC",
    VIDEO_QUALITY_SHORTS = "VIDEO_QUALITY_SHORTS",
    VIDEO_QUALITY_PRO = "VIDEO_QUALITY_PRO",

